name: constrained_layout
description: "A flexible Flutter layout allowing to position widgets by declaring relations between them."
version: 0.0.2
homepage: https://github.com/tomwyr/constrained-layout

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
